apiVersion: apps/v1
kind: Deployment
metadata:
  name: manage-app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manage-app-v1
  template:
    metadata:
      labels:
        app: manage-app-v1
    spec:
      containers:
        - name: manage-app-v1
          image: lautaro124/manage_app:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            initialDelaySeconds: 2
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo
          image: mongo:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
          - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

